import angular from 'angular-eslint';
import { defineConfig } from 'eslint/config';
import stylistic from '@stylistic/eslint-plugin';
import unusedImports from 'eslint-plugin-unused-imports';

import multilineArrowBody from './scripts/eslint-rules/multiline-arrow-body.js';

export default defineConfig(
  {
    ignores: ['coverage/**', 'dist/**', 'node_modules/**', 'website/.docusaurus/**', 'website/build/**'],
  },
  {
    files: ['src/**/*.ts'],
    extends: [...angular.configs.tsRecommended],
    processor: angular.processInlineTemplates,
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.spec.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@stylistic': stylistic,
      'unused-imports': unusedImports,
      'project': { rules: { 'multiline-arrow-body': multilineArrowBody } },
    },
    rules: {
      '@angular-eslint/component-selector': ['error', { type: 'element', prefix: 'gem', style: 'kebab-case' }],
      '@angular-eslint/consistent-component-styles': ['error', 'string'],
      '@angular-eslint/directive-selector': ['error', { type: 'attribute', prefix: 'form', style: 'camelCase' }],
      '@angular-eslint/no-input-rename': 'off',
      '@angular-eslint/no-output-native': 'error',
      '@angular-eslint/no-uncalled-signals': 'error',
      '@angular-eslint/prefer-inject': 'warn',
      '@angular-eslint/prefer-signals': ['warn', { preferReadonlySignalProperties: false }],
      '@angular-eslint/prefer-standalone': 'off',
      '@angular-eslint/sort-keys-in-type-decorator': ['error', {
        Component: [
          'selector',
          'templateUrl',
          'template',
          'styles',
          'styleUrl',
          'styleUrls',
          'standalone',
          'changeDetection',
          'encapsulation',
          'animations',
          'imports',
          'providers',
          'host',
          'viewProviders',
          'hostDirectives',
          'inputs',
          'outputs',
          'schemas',
          'exportAs',
          'queries',
          'preserveWhitespaces',
          'jit',
          'moduleId',
          'interpolation',
        ],
        NgModule: ['id', 'imports', 'declarations', 'providers', 'exports', 'bootstrap', 'schemas', 'jit'],
      }],
      '@angular-eslint/use-lifecycle-interface': 'off',
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
      '@stylistic/arrow-spacing': ['error', { before: true, after: true }],
      '@stylistic/block-spacing': ['error', 'always'],
      '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
      '@stylistic/comma-dangle': ['error', {
        arrays: 'always-multiline',
        functions: 'only-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
      }],
      '@stylistic/comma-spacing': ['error', { before: false, after: true }],
      '@stylistic/computed-property-spacing': ['error', 'never'],
      '@stylistic/dot-location': ['error', 'property'],
      '@stylistic/eol-last': 'error',
      '@stylistic/function-call-spacing': ['error', 'never'],
      '@stylistic/indent': ['error', 2, {
        ArrayExpression: 'first',
        ObjectExpression: 'first',
        FunctionDeclaration: { parameters: 'first' },
        FunctionExpression: { parameters: 'first' },
        SwitchCase: 1,
        MemberExpression: 1,
        ignoreComments: true,
        ignoredNodes: [
          'CallExpression > ArrowFunctionExpression > BlockStatement',
          'CallExpression > FunctionExpression > BlockStatement',
          'PropertyDefinition > ObjectExpression',
          'PropertyDefinition > ArrayExpression',
          'TemplateLiteral > ConditionalExpression',
        ],
      }],
      '@stylistic/key-spacing': ['error', { mode: 'strict', beforeColon: false, afterColon: true }],
      '@stylistic/keyword-spacing': ['error', { before: true, after: true }],
      '@stylistic/member-delimiter-style': ['error', {
        multiline: { delimiter: 'semi', requireLast: true },
        singleline: { delimiter: 'semi', requireLast: false },
        multilineDetection: 'brackets',
      }],
      '@stylistic/new-parens': ['error', 'always'],
      '@stylistic/no-extra-semi': 'error',
      '@stylistic/no-multi-spaces': 'error',
      '@stylistic/no-multiple-empty-lines': ['error', { max: 1 }],
      '@stylistic/no-trailing-spaces': ['error', { ignoreComments: true }],
      '@stylistic/object-curly-newline': ['warn', { ImportDeclaration: 'never' }],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/operator-linebreak': ['error', 'before', { overrides: { '=': 'after' } }],
      '@stylistic/padded-blocks': ['error', { blocks: 'never', classes: 'never', switches: 'never' }],
      '@stylistic/quotes': ['error', 'single', { allowTemplateLiterals: 'always' }],
      '@stylistic/rest-spread-spacing': ['error', 'never'],
      '@stylistic/semi-spacing': 'error',
      '@stylistic/space-before-blocks': 'error',
      '@stylistic/space-before-function-paren': ['error', { named: 'never', anonymous: 'always' }],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/space-infix-ops': 'error',
      '@stylistic/space-unary-ops': 'error',
      '@stylistic/spaced-comment': ['error', 'always', { markers: ['/'] }],
      '@stylistic/template-curly-spacing': ['error', 'never'],
      '@stylistic/type-annotation-spacing': 'error',
      '@stylistic/type-generic-spacing': 'error',
      '@stylistic/type-named-tuple-spacing': 'error',
      camelcase: ['error', { ignoreDestructuring: true }],
      eqeqeq: ['error', 'always'],
      'no-duplicate-imports': 'error',
      'no-eval': 'error',
      'no-new-wrappers': 'error',
      'no-param-reassign': 'error',
      'no-var': 'error',
      'one-var': ['error', 'never'],
      'prefer-const': 'error',
      'project/multiline-arrow-body': 'error',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': ['warn', {
        varsIgnorePattern: '^_',
        argsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
    },
  },
  {
    files: ['src/**/*.spec.ts'],
    rules: {
      '@angular-eslint/component-selector': 'off',
      '@angular-eslint/directive-selector': 'off',
    },
  },
  // Enable this block when the project adds components or external templates that should be linted.
  // {
  //   files: ['src/**/*.html'],
  //   extends: [...angular.configs.templateRecommended],
  //   rules: {
  //     '@angular-eslint/template/eqeqeq': 'off',
  //     '@angular-eslint/template/no-any': 'warn',
  //     '@angular-eslint/template/no-duplicate-attributes': ['error', { ignore: ['class'] }],
  //     '@angular-eslint/template/no-interpolation-in-attributes': ['error', { allowSubstringInterpolation: true }],
  //     '@angular-eslint/template/no-negated-async': 'off',
  //     '@angular-eslint/template/prefer-control-flow': 'warn',
  //     '@angular-eslint/template/prefer-self-closing-tags': 'error',
  //     '@angular-eslint/template/prefer-template-literal': 'warn',
  //   },
  // },
);
