// Generated by scripts/sync-public-type-reference.mjs.
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const publicTypesSidebar: SidebarsConfig[string] = [
  {
    "type": "category",
    "label": "Nodes and values",
    "items": [
      "reference/types/added-node",
      "reference/types/any-node",
      "reference/types/array-indexes",
      "reference/types/array-item-node",
      "reference/types/array-items",
      "reference/types/array-item-with-parent",
      "reference/types/array-node",
      "reference/types/array-patch",
      "reference/types/array-set",
      "reference/types/array-value",
      "reference/types/dynamic-form-children",
      "reference/types/dynamic-node",
      "reference/types/field-node",
      "reference/types/form-node",
      "reference/types/form-node-value",
      "reference/types/form-patch",
      "reference/types/form-set",
      "reference/types/form-value",
      "reference/types/form-value-contract",
      "reference/types/group-node",
      "reference/types/group-patch",
      "reference/types/group-set",
      "reference/types/group-value",
      "reference/types/node-value-signal"
    ]
  },
  {
    "type": "category",
    "label": "Node APIs",
    "items": [
      "reference/types/array-api",
      "reference/types/callable-node-api",
      "reference/types/field-api",
      "reference/types/form-api",
      "reference/types/group-api",
      "reference/types/node-api",
      "reference/types/node-errors-signal"
    ]
  },
  {
    "type": "category",
    "label": "Controls and bindings",
    "items": [
      "reference/types/closest-form-state",
      "reference/types/control-error",
      "reference/types/control-state",
      "reference/types/control-state-disabled-reason",
      "reference/types/control-state-error",
      "reference/types/control-state-source",
      "reference/types/form-node-binding",
      "reference/types/form-node-checkbox-control",
      "reference/types/form-node-control",
      "reference/types/form-node-directive",
      "reference/types/form-node-errors-context",
      "reference/types/form-node-state-options",
      "reference/types/form-node-submit-event",
      "reference/types/form-node-ui-control",
      "reference/types/form-node-value-control"
    ]
  },
  {
    "type": "category",
    "label": "Validator contracts",
    "items": [
      "reference/types/async-validator",
      "reference/types/async-validator-api",
      "reference/types/async-validator-base-context",
      "reference/types/async-validator-context",
      "reference/types/async-validator-options",
      "reference/types/async-validator-state",
      "reference/types/composable-validator",
      "reference/types/field-context",
      "reference/types/parameterized-async-validator-config",
      "reference/types/parameterized-async-validator-context",
      "reference/types/parameterized-async-validator-options",
      "reference/types/validator",
      "reference/types/validator-api",
      "reference/types/validator-context",
      "reference/types/validator-options",
      "reference/types/validator-readonly-api",
      "reference/types/validators",
      "reference/types/validator-source"
    ]
  },
  {
    "type": "category",
    "label": "Validation errors and results",
    "items": [
      "reference/types/async-validation-result",
      "reference/types/built-in-validation-error",
      "reference/types/composable-validation-result",
      "reference/types/custom-validation-error",
      "reference/types/validation-error",
      "reference/types/validation-error-for-kind",
      "reference/types/validation-error-map",
      "reference/types/validation-error-with-optional-target-node",
      "reference/types/validation-error-without-target-node",
      "reference/types/validation-error-with-target-node",
      "reference/types/validation-result",
      "reference/types/validation-status",
      "reference/types/validation-success",
      "reference/types/validator-error"
    ]
  },
  {
    "type": "category",
    "label": "Configuration",
    "items": [
      "reference/types/array-options",
      "reference/types/disabled-reason",
      "reference/types/disabled-state-source",
      "reference/types/field-options",
      "reference/types/form-nodes-config",
      "reference/types/form-options",
      "reference/types/global-form-nodes-config",
      "reference/types/group-options",
      "reference/types/mark-as-touched-options",
      "reference/types/sync-input-name",
      "reference/types/sync-inputs",
      "reference/types/validator-message-parameters",
      "reference/types/validator-messages"
    ]
  },
  {
    "type": "category",
    "label": "Configured factories",
    "items": [
      "reference/types/array-factory",
      "reference/types/field-factory",
      "reference/types/form-factory",
      "reference/types/form-primitives",
      "reference/types/form-primitives-options",
      "reference/types/group-factory",
      "reference/types/non-nullable-field-factory"
    ]
  },
  {
    "type": "category",
    "label": "Observable interoperability",
    "items": [
      "reference/types/observable-like",
      "reference/types/observer-like",
      "reference/types/subscription-like"
    ]
  }
];

export default publicTypesSidebar;
