import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  consumerDocs: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: ['getting-started/installation', 'getting-started/first-form'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      link: { type: 'doc', id: 'tutorial/index' },
      items: [
        'tutorial/model',
        'tutorial/bind-controls',
        'tutorial/validation',
        'tutorial/nesting-and-state',
        'tutorial/dynamic-arrays',
        'tutorial/async-validation',
        'tutorial/submission',
      ],
    },
    {
      type: 'category',
      label: 'Core concepts',
      items: [
        'concepts/form-nodes',
        'concepts/creating-nodes',
        'concepts/tree-and-api',
        'concepts/values-and-state',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/choosing-a-primitive',
        'guides/form-modeling-patterns',
        'guides/validation',
        'guides/errors-and-status',
        'guides/async-validation',
        'guides/value-flow-and-debounce',
        'guides/interaction-and-availability',
        'guides/dynamic-object-children',
        'guides/dynamic-arrays',
        'guides/control-binding',
        'guides/custom-controls',
        'guides/custom-controls-advanced',
        'guides/submission',
        'guides/validator-messages',
        'guides/testing',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/api-overview',
        'reference/node-types',
        'reference/form',
        'reference/field',
        'reference/array',
        'reference/group',
        { type: 'doc', id: 'reference/form-node-state', label: 'useFormNodeState()' },
        { type: 'doc', id: 'reference/form-node-binding', label: '[formNode]' },
        'reference/form-nodes-module',
        'reference/configuration',
        'reference/node-api',
        {
          type: 'category',
          label: 'Other',
          items: [
            'reference/create-form-primitives',
            'reference/form-node-value',
            'reference/form-value-contract',
            'reference/provide-form-nodes-config',
            'reference/provide-form-node-pass-through',
            'reference/configure-global-form-nodes',
            'reference/angular-forms-status-classes',
            'reference/form-node-token',
          ],
        },
        {
          type: 'category',
          label: 'Validation',
          link: { type: 'doc', id: 'reference/validation' },
          items: [
            'reference/validator',
            'reference/async-validator',
            {
              type: 'category',
              label: 'Built-in validators',
              link: { type: 'doc', id: 'reference/built-in-validators' },
              items: [
                'reference/validators/required',
                'reference/validators/required-if',
                'reference/validators/min',
                'reference/validators/max',
                'reference/validators/between',
                'reference/validators/integer',
                'reference/validators/min-length',
                'reference/validators/max-length',
                'reference/validators/min-words',
                'reference/validators/max-words',
                'reference/validators/pattern',
                'reference/validators/email',
                'reference/validators/url',
                'reference/validators/min-date',
                'reference/validators/max-date',
                'reference/validators/date-between',
                'reference/validators/one-of',
                'reference/validators/equal-to',
                'reference/validators/unique-items',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/behavior-details'],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['integrations/angular-material', 'integrations/primeng'],
    },
    {
      type: 'category',
      label: 'Help',
      items: ['help/common-mistakes', 'help/troubleshooting'],
    },
    {
      type: 'category',
      label: 'Project',
      items: [
        'project/versioning',
        'project/compatibility',
        'project/changelog',
        'project/migrations',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: ['examples/executable-examples', 'examples/complex-form'],
    },
    {
      type: 'category',
      label: 'Cookbook',
      link: { type: 'doc', id: 'cookbook/index' },
      items: [
        'cookbook/password-confirmation',
        'cookbook/conditional-fields',
        'cookbook/edit-server-data',
        'cookbook/reorderable-arrays',
        'cookbook/remote-validation',
        'cookbook/multi-step-form',
        'cookbook/localized-messages',
        'cookbook/custom-rating-control',
      ],
    },
  ],
};

export default sidebars;
