import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  consumerDocs: [
    'index',
    'playground',
    {
      type: 'category',
      label: 'Getting started',
      items: ['getting-started/installation', 'getting-started/first-form'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      link: { type: 'doc', id: 'tutorial/index' },
      items: [
        'tutorial/model',
        'tutorial/bind-controls',
        'tutorial/validation',
        'tutorial/nesting-and-state',
        'tutorial/dynamic-arrays',
        'tutorial/async-validation',
        'tutorial/submission',
      ],
    },
    {
      type: 'category',
      label: 'Core concepts',
      items: [
        'concepts/form-nodes',
        'concepts/creating-nodes',
        'concepts/tree-and-api',
        'concepts/values-and-state',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/choosing-a-primitive',
        'guides/form-modeling-patterns',
        'guides/validation',
        'guides/errors-and-status',
        'guides/async-validation',
        'guides/value-flow-and-debounce',
        'guides/interaction-and-availability',
        'guides/dynamic-object-children',
        'guides/dynamic-arrays',
        'guides/control-binding',
        'guides/custom-controls',
        'guides/submission',
        'guides/validator-messages',
        'guides/testing',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/api-overview',
        'reference/form',
        'reference/field',
        'reference/array',
        'reference/group',
        'reference/control-state',
        { type: 'doc', id: 'reference/form-node-binding', label: '[formNode]' },
        'reference/configuration',
        'reference/node-api',
        {
          type: 'category',
          label: 'Other',
          items: [
            'reference/provide-form-node-config',
            'reference/provide-form-node-pass-through',
            'reference/provide-validator-messages',
            'reference/configure-global-validator-messages',
            'reference/angular-forms-status-classes',
            'reference/form-node-token',
          ],
        },
        {
          type: 'category',
          label: 'Validation',
          link: { type: 'doc', id: 'reference/validation' },
          items: [
            'reference/validator',
            'reference/async-validator',
            {
              type: 'category',
              label: 'Built-in validators',
              link: { type: 'doc', id: 'reference/built-in-validators' },
              items: [
                { type: 'link', label: 'required', href: '/reference/built-in-validators#required' },
                { type: 'link', label: 'min', href: '/reference/built-in-validators#min' },
                { type: 'link', label: 'max', href: '/reference/built-in-validators#max' },
                { type: 'link', label: 'between', href: '/reference/built-in-validators#between' },
                { type: 'link', label: 'integer', href: '/reference/built-in-validators#integer' },
                { type: 'link', label: 'minLength', href: '/reference/built-in-validators#minlength' },
                { type: 'link', label: 'maxLength', href: '/reference/built-in-validators#maxlength' },
                { type: 'link', label: 'minWords', href: '/reference/built-in-validators#minwords' },
                { type: 'link', label: 'maxWords', href: '/reference/built-in-validators#maxwords' },
                { type: 'link', label: 'pattern', href: '/reference/built-in-validators#pattern' },
                { type: 'link', label: 'email', href: '/reference/built-in-validators#email' },
                { type: 'link', label: 'url', href: '/reference/built-in-validators#url' },
                { type: 'link', label: 'minDate', href: '/reference/built-in-validators#mindate' },
                { type: 'link', label: 'maxDate', href: '/reference/built-in-validators#maxdate' },
                { type: 'link', label: 'dateBetween', href: '/reference/built-in-validators#datebetween' },
                { type: 'link', label: 'oneOf', href: '/reference/built-in-validators#oneof' },
                { type: 'link', label: 'equalTo', href: '/reference/built-in-validators#equalto' },
                { type: 'link', label: 'uniqueItems', href: '/reference/built-in-validators#uniqueitems' },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/behavior-details'],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['integrations/angular-material', 'integrations/primeng'],
    },
    {
      type: 'category',
      label: 'Help',
      items: ['help/common-mistakes', 'help/troubleshooting'],
    },
    {
      type: 'category',
      label: 'Project',
      items: [
        'project/versioning',
        'project/compatibility',
        'project/changelog',
        'project/migrations',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: ['examples/executable-examples', 'examples/complex-form'],
    },
    {
      type: 'category',
      label: 'Cookbook',
      link: { type: 'doc', id: 'cookbook/index' },
      items: [
        'cookbook/password-confirmation',
        'cookbook/conditional-fields',
        'cookbook/edit-server-data',
        'cookbook/reorderable-arrays',
        'cookbook/remote-validation',
        'cookbook/multi-step-form',
        'cookbook/localized-messages',
        'cookbook/custom-rating-control',
      ],
    },
  ],
};

export default sidebars;
