import { expect, vi } from 'vitest';
import { By } from '@angular/platform-browser';
import type { ComponentFixture } from '@angular/core/testing';

import type { AnyNode, FormNodeBinding } from '../../src/public-api';
import type { SignalBindingHost } from '../integration/signal-binding.fixture';
import type { OutputCvaControl } from '../integration/value-change-outputs.fixture';
import type { OrderedValueControl, OrderedCheckboxControl, OrderedPairControl } from '../integration/custom-event-order.fixture';

export const assertSignalBinding = (fixture: ComponentFixture<SignalBindingHost>) => {
  fixture.detectChanges();
  const host = fixture.componentInstance;
  const input = fixture.nativeElement.querySelector('#text') as HTMLInputElement;
  const shared = fixture.nativeElement.querySelector('#shared') as HTMLInputElement;
  const check = fixture.nativeElement.querySelector('#check') as HTMLInputElement;
  const custom = fixture.debugElement.query(By.css('ordered-value')).componentInstance as OrderedValueControl;
  const checkbox = fixture.debugElement.query(By.css('ordered-check')).componentInstance as OrderedCheckboxControl;
  const cva = fixture.debugElement.query(By.css('output-cva')).componentInstance as OutputCvaControl;
  const binding = fixture.debugElement.query(By.css('#text')).references['textBinding'] as FormNodeBinding<AnyNode>;
  expect(input.value).toBe('initial');
  expect(binding.node().$api.pristine()).toBe(true);
  expect(host.commits).toEqual([]);
  host.text.set('service');
  fixture.detectChanges();
  expect(input.value).toBe('service');
  expect(shared.value).toBe('service');
  expect(binding.node().$api.pristine()).toBe(true);
  expect(host.commits).toEqual([]);
  input.value = 'edited';
  input.dispatchEvent(new Event('input'));
  expect(host.text()).toBe('edited');
  expect(host.observations).toEqual(['edited']);
  expect(host.commits).toEqual(['edited']);
  expect(binding.node().$api.dirty()).toBe(true);
  fixture.detectChanges();
  expect(shared.value).toBe('edited');
  const otherBinding = fixture.debugElement.query(By.css('#shared')).references['sharedBinding'] as FormNodeBinding<AnyNode>;
  expect(otherBinding.node().$api.pristine()).toBe(true);
  host.afterCommit = () => host.text.set('consumer override');
  input.value = 'before override';
  input.dispatchEvent(new Event('input'));
  expect(host.text()).toBe('consumer override');
  fixture.detectChanges();
  expect(input.value).toBe('consumer override');
  expect(shared.value).toBe('consumer override');
  delete host.afterCommit;
  const number = fixture.nativeElement.querySelector('#number') as HTMLInputElement;
  expect(number.value).toBe('');
  number.value = '42';
  number.dispatchEvent(new Event('input'));
  expect(host.amount()).toBe(42);
  number.value = '';
  number.dispatchEvent(new Event('input'));
  expect(host.amount()).toBeNull();
  const pair = fixture.debugElement.query(By.css('ordered-pair')).componentInstance as OrderedPairControl;
  pair.valueChange.emit('pair edit');
  expect(host.pair()).toBe('pair edit');
  expect(host.pairs).toEqual(['pair edit']);
  host.pair.set('pair service');
  fixture.detectChanges();
  expect(pair.value()).toBe('pair service');
  expect(host.pairs).toEqual(['pair edit']);
  check.checked = true;
  check.dispatchEvent(new Event('change'));
  expect(host.checked()).toBe(true);
  fixture.detectChanges();
  expect(checkbox.checked()).toBe(true);
  checkbox.checked.set(false);
  expect(host.checks.at(-1)).toBe(false);
  expect(host.checked()).toBe(false);
  custom.selection.set({ name: 'Bea' });
  expect(host.person()).toEqual({ name: 'Bea' });
  expect(host.names.at(-1)).toBe('Bea');
  host.person.set({ name: 'service object' });
  fixture.detectChanges();
  expect(custom.selection()).toEqual({ name: 'service object' });
  host.objectSource.set(host.form);
  fixture.detectChanges();
  custom.selection.set({ name: 'aggregate edit' });
  expect(host.form()).toEqual({ name: 'aggregate edit' });
  expect(host.form.dirty()).toBe(true);
  expect(host.person()).toEqual({ name: 'service object' });
  host.objectSource.set(host.person);
  fixture.detectChanges();
  expect(custom.selection()).toEqual({ name: 'service object' });
  const writes = vi.spyOn(cva, 'writeValue');
  cva.onChange('CVA edit');
  expect(host.cva()).toBe('CVA edit');
  expect(host.cvaValues.at(-1)).toBe('CVA edit');
  fixture.detectChanges();
  expect(writes).not.toHaveBeenCalled();
  host.cva.set('CVA service');
  fixture.detectChanges();
  expect(cva.value).toBe('CVA service');
  expect(host.cvaValues).toEqual(['CVA edit']);
  host.active.set(host.replacement);
  fixture.detectChanges();
  expect(input.value).toBe('replacement');
  host.text.set('old source');
  fixture.detectChanges();
  expect(input.value).toBe('replacement');
  input.value = 'new source';
  input.dispatchEvent(new Event('input'));
  expect(host.replacement()).toBe('new source');
  expect(host.text()).toBe('old source');
  host.active.set(host.field);
  fixture.detectChanges();
  input.value = 'field edit';
  input.dispatchEvent(new Event('input'));
  expect(host.field()).toBe('field edit');
  expect(host.replacement()).toBe('new source');
  host.active.set(host.text);
  fixture.detectChanges();
  expect(input.value).toBe('old source');
  expect(binding.node().$api.pristine()).toBe(true);
  fixture.destroy();
  const snapshot = host.cva();
  cva.onChange('destroyed');
  expect(host.cva()).toBe(snapshot);
  input.value = 'destroyed';
  input.dispatchEvent(new Event('input'));
  expect(host.text()).toBe('old source');
  host.text.set('after destruction');
  expect(input.value).toBe('destroyed');
};
